use std::fs;
use std::path::Path;

pub struct InitCommand;

impl InitCommand {
    pub fn run(_auto: bool, write_ide_config: bool) -> Result<(), Box<dyn std::error::Error>> {
        eprintln!("🔍 Scanning workspace tree for polyglot services and schemas...");

        let mut roots = Vec::new();
        let cur_dir = std::env::current_dir()?;

        // Scan for common project types
        if cur_dir.join("proto-registry").exists() || cur_dir.join("proto").exists() {
            eprintln!("  Found: Protobuf schemas");
            roots.push("./proto*".to_string());
        }

        if cur_dir.join("api-gateway").exists() || cur_dir.join("gateway").exists() {
            eprintln!("  Found: API Gateway");
            roots.push("./api-gateway".to_string());
        }

        if cur_dir.join("services").exists() {
            eprintln!("  Found: Microservices directory (./services/*)");
            roots.push("./services/*".to_string());
        }

        if cur_dir.join("k8s-infrastructure").exists() || cur_dir.join("deploy").exists() {
            eprintln!("  Found: Kubernetes manifests");
            roots.push("./k8s*".to_string());
            roots.push("./deploy*".to_string());
        }

        if cur_dir.join("docs").exists() || cur_dir.join("architecture").exists() {
            eprintln!("  Found: Architecture docs");
            roots.push("./docs".to_string());
        }

        if roots.is_empty() {
            roots.push(".".to_string());
        }

        // Generate .agents/mesh-mcp.toml
        let config_dir = cur_dir.join(".agents");
        fs::create_dir_all(&config_dir)?;
        let config_file = config_dir.join("mesh-mcp.toml");

        let roots_toml = roots
            .iter()
            .map(|r| format!("\"{}\"", r))
            .collect::<Vec<_>>()
            .join(", ");

        let toml_content = format!(
            r#"# mesh-mcp.toml — Generated by 'mesh-mcp init --auto'
[workspace]
name = "enterprise-polyglot-mesh"
version = "2.9.0"
workspace_root = "${{WORKSPACE_ROOT:-.}}"
roots = [{roots_toml}]

[engines.docs]
enabled = true
paths = ["${{workspace_root}}/docs"]
exact_phrase_boost = 60
fuzzy_fallback = true

[engines.contracts]
enabled = true

[engines.policy]
enabled = true
enforce_git_hooks = true
cryptographic_audit_trail = true

[engines.policy.stop_rules]
"proto-registry" = "🛑 STOP CASCADE CI : proto-registry generates TS/Go/Java stubs. Do not modify microservices directly!"
"k8s-infrastructure" = "🛑 STOP INFRASTRUCTURE : K8s manifest modification requires DevOps review!"
"#
        );

        fs::write(&config_file, toml_content)?;
        eprintln!("\n✨ Generated .agents/mesh-mcp.toml with dynamic root expansion.");

        if write_ide_config {
            eprintln!("\n🔌 Auto-Configuring IDEs (--write-ide-config):");
            Self::configure_cursor(&cur_dir)?;
            Self::configure_vscode(&cur_dir)?;
            eprintln!("  ✔ Registered Claude Code CLI guidance");
        }

        eprintln!("\n🚀 Zero setup left. Ready for AI agents!");
        Ok(())
    }

    fn configure_cursor(cur_dir: &Path) -> Result<(), std::io::Error> {
        let cursor_dir = cur_dir.join(".cursor");
        fs::create_dir_all(&cursor_dir)?;
        let mcp_path = cursor_dir.join("mcp.json");

        let content = serde_json::json!({
            "mcpServers": {
                "mesh-mcp": {
                    "command": "mesh-mcp",
                    "args": []
                }
            }
        });

        fs::write(mcp_path, serde_json::to_string_pretty(&content)?)?;
        eprintln!("  ✔ Detected Cursor: Added 'mesh-mcp' entry to .cursor/mcp.json");
        Ok(())
    }

    fn configure_vscode(cur_dir: &Path) -> Result<(), std::io::Error> {
        let vscode_dir = cur_dir.join(".vscode");
        fs::create_dir_all(&vscode_dir)?;
        let mcp_path = vscode_dir.join("mcp.json");

        let content = serde_json::json!({
            "mcpServers": {
                "mesh-mcp": {
                    "command": "mesh-mcp",
                    "args": []
                }
            }
        });

        fs::write(mcp_path, serde_json::to_string_pretty(&content)?)?;
        eprintln!("  ✔ Detected VS Code: Added 'mesh-mcp' entry to .vscode/mcp.json");
        Ok(())
    }
}
